require:
  - rubocop-rake
  - rubocop-minitest

AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
Style/HashSyntax:
  Exclude:
    - Rakefile
Layout/SpaceInsideParens:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - test/**/*_test.rb

Gemspec/OrderedDependencies:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Gemspec/RequireMFA:
  Enabled: false
Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
